# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Overview
    url: /#overview
    weight: 20
  - name: Dashboard
    url: /#dashboard
    weight: 20
  - name: Highlights
    url: /#highlights
    weight: 30
  - name: Resources
    url: /#Resources
    weight: 40
